### PR TITLE
add frontpage

### PR DESCRIPTION
**Pull request by jrwren**
for #1

### CODE REVIEW

**Comment by jrwren** [comment]
I have it running here: https://is-it-the-winter-break-yet.glitch.me

**Comment by rlespinasse** [comment]
Nice one
Can you add the dates of the winter break?

**Comment by thuguerre** [comment]
> 
> 
> I have it running here: https://is-it-the-winter-break-yet.glitch.me

I do not know where the bug comes from, but https://is-it-the-winter-break-yet.glitch.me returns `NO`, while the called service https://europe-west1-winter-break.cloudfunctions.net/IsItTheWinterBreakYet returns `TRUE` (or I may just have do not understand something...).

**Comment by rlespinasse** [comment]
@thuguerre good catch, it's a CORS issue

```
Access to fetch at 'https://europe-west1-winter-break.cloudfunctions.net/IsItTheWinterBreakYet' from origin 'https://is-it-the-winter-break-yet.glitch.me' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

**Comment by jrwren** [comment]
I'll add some dates, and yes, while I have it "running" over at glitch it won't work until the service is updated to allow CORS, or the index.html is deployed to the same domain. Is it possible that the index.html could be served by a function at `https://europe-west1-winter-break.cloudfunctions.net/` ?

**Comment by rlespinasse** [comment]
I currently checking this point, stay tune.

**Comment by an0rak-dev** [comment]
Hi everyone ! 

@rlespinasse you can check #4 to allow CORS requests in your Cloud Function.

@jrwren I think you have a bug in your code. Your `blah` function will return `response.json()` which is a Promise. That's why in your example, you always have `NO` since the code isn't valid. If you resolve the Promise, it works fine :) 
```
var main = document.querySelector("#main");
    async function blah() {
      let response = await fetch(
        "https://europe-west1-rich-experience-219613.cloudfunctions.net/IsItTheWinterBreakYet"
      );
      let isitJson = await response.json();
      return isitJson;
    }
    blah().then(isitJson => {
         let isit = isitJson.is_winter_break_yet;
         if (isit) {
           main.innerHTML = "YES";
         } else {
           main.innerHTML = "NO";
         }
       });
```

**Comment by jrwren** [comment]
I don't think so.

It is awaited using `await` which resolves the promise.

**Comment by jrwren** [comment]
Updated with dates.

**Comment by an0rak-dev** [comment]
> I don't think so.
> 
> It is awaited using `await` which resolves the promise.

Yup, your right, I skip this `await` 😅

**Pull request merged**
